env:
  browser: true
  es2021: true
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
parserOptions:
  ecmaVersion: 2020
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] 
